### ISSUE TITLE
財務報表編輯：pdf連結失效

### ISSUE THREAD

**Issue by Helen-R** [joanne3634/smartdonor-issue-tracker#1]
199
297
334
488-2013
505
540
603-2014
937
1885

**Comment by RexChip** [comment]
471
488-2014

**Comment by RexChip** [comment]
778-2014

**Comment by RexChip** [comment]
808
878
921
937
969
2390
2391

**Comment by RexChip** [comment]
1040-2014
1126

**Comment by RexChip** [comment]
2051
2211
2297

**Comment by Helen-R** [comment]
[twnpos.xlsx](https://github.com/joanne3634/smartdonor-issue-tracker/files/234045/twnpos.xlsx)

組織改名：手動處理對照
自律聯盟連結失效：希望可以mark起來，重新crawl的時候可以檢查

**Comment by RexChip** [comment]
1309 無法讀取

**Comment by Helen-R** [comment]
已合併
